//seeders: data used for initial population in a db. Used for testing, ex. we wouldn't use this in a working app, but I just made it to see if code works
const generatedCodes = [
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
  'jake',
  'tim',
  'andrew',
  'jason',
];

module.exports = generatedCodes;
